### ISSUE TITLE
Saving archive results in an incorrect "cannot be archived by wayback machine as it is a redirect" failure

### ISSUE THREAD

**Issue by dequeued0** [akamhy/waybackpy#108]
I tried upgrading from 2.4.2 to 2.4.4 and the first page I tried to archive returned a new error:

```
archive of https://old.reddit.com/r/personalfinance/comments/s4gdfx/how_i_recovered_my_50k_investment_stolen_off/ failed: URL cannot be archived by wayback machine as it is a redirect.
Header:
save redirected
```

This page is not a redirect. It appears that the archive actually worked, though. It's successfully archived on archive.org with a timestamp that is about the same timestamp as the above error in my log.

**Comment by akamhy** [comment]
Should be fixed in [v.3.0.0](https://github.com/akamhy/waybackpy/releases/tag/3.0.0).

**Comment by akamhy** [comment]
Closing, if the issue persists reopen.
