### ISSUE TITLE
make available in conda-forge

### ISSUE THREAD

**Issue by rafaelrdealmeida** [akamhy/waybackpy#111]
Hi, are there any plans to make waybackpy available in conda-forge?

cheers

**Comment by akamhy** [comment]
@rafaelrdealmeida No and most likely not in 2022, but if you want you can create a PR at <https://github.com/conda-forge/staged-recipes>. I can link to it from the Readme of this repo.

Similar case:

I had no plans to create a docker image but SecSI (https://secsi.io), an Italian cybersecurity startup created a docker image and it is in fact [linked from the readme of the repo](https://github.com/akamhy/waybackpy#-docker-image).

**Comment by rafaelrdealmeida** [comment]
Hi @akamhy , I will do this within a week!

Thanks for keeping waybackpy. He is very helpful to us!

####

If someone is using the anaconda virtual environment through the yaml file in the linux terminal:

```
conda config --set pip_interop_enabled True
```

and see : https://github.com/conda/conda/issues/10815#issuecomment-890382518

**Comment by rafaelrdealmeida** [comment]
update:

https://github.com/conda-forge/staged-recipes/pull/17634

**Comment by rafaelrdealmeida** [comment]
hi, how should I proceed? [conda-forge/staged-recipes#17634](https://github.com/conda-forge/staged-recipes/pull/17634)

Nicholas Bollweg @bollwyvl 20:49
had to do this relatively recently: one option is to [patch](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#patches) in open(encoding="utf-8")

Nicholas Bollweg @bollwyvl 20:51
I tackled it by:
 - making an upstream PR
   - [Changaco/python-libarchive-c#120](https://github.com/Changaco/python-libarchive-c/pull/120)
- using that diff in a feedstock
  - https://github.com/conda-forge/python-libarchive-c-feedstock/pull/31/files#diff-f29d42418484d3859423203ab78fdacb29dabab3df330d82290c26fd83c24bf9

**Comment by akamhy** [comment]
PR https://github.com/akamhy/waybackpy/pull/114 is now merged, I believe now there should be no more issues.

**Comment by akamhy** [comment]
> PR #114 is now merged, I believe now there should be no more issues.

Okay, I was wrong. see https://github.com/akamhy/waybackpy/pull/114/files#r791431485

Also I should add a build test along with the code-style and unittests. I also failed to catch the syntax issue.

**Comment by akamhy** [comment]
> Also I should add a build test along with the code-style and unittests. I also failed to catch the syntax issue.

Build test added <https://github.com/akamhy/waybackpy/pull/118>.

**Comment by rafaelrdealmeida** [comment]
see: https://github.com/conda-forge/staged-recipes/pull/17643

**Comment by rafaelrdealmeida** [comment]
@akamhy , how is the figlet generated? https://github.com/akamhy/waybackpy/blob/4408c5e2ca8b875fff8db13d8172c5f025b1127e/waybackpy/cli.py#L172-L179

see: https://github.com/conda-forge/staged-recipes/pull/17643#issuecomment-1021532562

**Comment by akamhy** [comment]
> @akamhy , how is the figlet generated?

I don't remember but it was possibly from some website and it is not in ASCII characters.

Maybe I should replace it with the ASCII version below and create a new release? @rafaelrdealmeida 
```
                     _                _                
                    | |              | |               
__      ____ _ _   _| |__   __ _  ___| | ___ __  _   _ 
\ \ /\ / / _` | | | | '_ \ / _` |/ __| |/ / '_ \| | | |
 \ V  V / (_| | |_| | |_) | (_| | (__|   <| |_) | |_| |
  \_/\_/ \__,_|\__, |_.__/ \__,_|\___|_|\_\ .__/ \__, |
                __/ |                     | |     __/ |
               |___/                      |_|    |___/ 
```

**Comment by akamhy** [comment]
I have replaced the non-figlet with ASCII figlet. See https://github.com/akamhy/waybackpy/commit/5ea1d3ba4f8f3ba75a47d12c3126ea21970d7c7c

**Comment by rafaelrdealmeida** [comment]
@akamhy now it's gone, thanks a lot for the help! I put you on the maintainers list too.

When the package is published on conda-forge. I can add this in the  "Installation" item if you want

cheers

**Comment by rafaelrdealmeida** [comment]
- [ ] add conda-forge in the "Installation"

**Comment by rafaelrdealmeida** [comment]
I added description in the meta.yaml of the conda-forge package. I believe it helps that more people find the package

https://github.com/conda-forge/waybackpy-feedstock/blob/master/recipe/meta.yaml
