### ISSUE TITLE
DeepSource: ignore meaningless rules

### ISSUE THREAD

**Issue by eggplants** [akamhy/waybackpy#144]
Currently, https://deepsource.io/gh/akamhy/waybackpy/ reports some linted errors.
Please ignore some false positive and meaningless rules.

ref1: https://deepsource.io/blog/release-ignore-issues-in-test-files/
ref2: https://discuss.deepsource.io/t/using-assert-outside-tests/79/4

**Comment by akamhy** [comment]
Done
