### ISSUE TITLE
README.md non-ASCII character and build

### ISSUE THREAD

**Issue by akamhy** [akamhy/waybackpy#147]
**Describe the bug**
For the build process to succeed in windows the encoding should be explicitly set to `UTF-8`. It is guaranteed to fail otherwise, a similar incident happened on conda-forge and now see <https://github.com/akamhy/videohash/pull/83>.

The following line is a must for the package to be buildable on windows.
https://github.com/akamhy/waybackpy/blob/7ac9353f74a4d44b1b69e6b19cdda3451eb3db5f/setup.py#L5

But https://github.com/akamhy/waybackpy/commit/e61447effddb1ab5d68e58ff07420f18f47a1c5b#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7 moved all stuff from setup.py to setup.cfg.
This means the build will fail on windows as we are not explicitly telling to set encoding to `UTF-8`.

**What non-ASCII stuff in README.md**
Emojis

**Possible fix**

Revert  https://github.com/akamhy/waybackpy/commit/e61447effddb1ab5d68e58ff07420f18f47a1c5b#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

OR

Remove emojis from README.md

OR

https://github.com/pypa/setuptools/issues/1702

**Version:**

- OS: Windows
- Version: Current
- Is the latest version? Yes

**Comment by akamhy** [comment]
I am for removing emojis from README.md

**Comment by eggplants** [comment]
It's messy workaround, but how about replacing emoji with images?

**Comment by eggplants** [comment]
#### <img src="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/joypixels/291/gear_2699-fe0f.png" width=10 height=10></img> Test

**Comment by akamhy** [comment]
> It's messy workaround, but how about replacing emoji with images?

How do you do that? Isn't it impossible to add images in the heading in GitHub?

**Comment by akamhy** [comment]
Okay, it is possible. Thanks.

**Comment by eggplants** [comment]
recommendation: https://emojipedia.org

**Comment by akamhy** [comment]
> recommendation: https://emojipedia.org

Sorry, but using GitHub-hosted equivalent emojis appears to be a better Idea. Nothing will change for the end-user as we will be using the same images they were served before(GitHub replaces emojis with equivalent images).
