### ISSUE TITLE
Does the CLI *request* Wayback to archive the page?

### ISSUE THREAD

**Issue by DGaffney** [akamhy/waybackpy#172]
When I run the `waybackpy` CLI with the following command:

```
root@server:~/repo# waybackpy --url "https://example.com/some-unique-path" --save
Archive URL:
https://web.archive.org/web/1234567890/https://example.com/some-unique-path
Cached save:
False
```

Am I asking that Internet archive produce a snapshot of the page? At some point later, can I visit https://web.archive.org/web/1234567890/https://example.com/some-unique-path to see that snapshot once a machine has taken the snapshot?

**Comment by akamhy** [comment]
> Am I asking that Internet archive produce a snapshot of the page? 

Yes

> At some point later, can I visit https://web.archive.org/web/1234567890/https://example.com/some-unique-path to see that snapshot once a machine has taken the snapshot?

Yes
