### ISSUE TITLE
One question about the return time value

### ISSUE THREAD

**Issue by Huo-Yuan** [akamhy/waybackpy#177]
For example, using **oldest.datetime_timestamp**, **I can get the time 2021-01-01 15:51:57.**

However, I do not know which time zone it belongs to?

BTW, the oldest time is the time when the webpage was first published or first captured

**Comment by akamhy** [comment]
time zone = UTC
oldest time = First time the archive was captured, and not the day the webpage was published.

**Comment by Huo-Yuan** [comment]
Can I know the frequency of capture

**Comment by akamhy** [comment]
I'm not sure what you mean by frequency of capture, so I will give multiple answers. 
 
The first answer) The frequency of capture(new archive) depends on the webpage, Google's homepage for example is archived 100s of times a day but an obscure webpage may only have a single library if at all. Frequency is proportional to the popularity of the webpage.

The second Answer) The number of URLs you can submit to be Archived to the Wayback Machine, using the Save Page Now features, is a max of 15 per minute. 

The third Answer) Wayback Machine limits capture per webpage to 45 minutes. You need to wait 45 minutes between two successive capture for the same webpage. This time frame of 45 minute, may change in the future.

**Comment by Huo-Yuan** [comment]
Thanks a lot, that is exactly what I am looking for
