### ISSUE TITLE
add a way to get a list of all archives for a given URL

### ISSUE THREAD

**Issue by dequeued0** [akamhy/waybackpy#66]
Right now, there seems to be no way to list all of the available archives by timestamp. Unless I am missing something, the only options are to call `.oldest()`, `.newest()`, or request for an archive `.near()` a specific timestamp. It would be great if it was possible to get a list of all available archives which could then be individually fetched as desired with `.get()`, printed to get the archive URL, etc.

**Comment by akamhy** [comment]
@dequeued0 
Checkout <https://github.com/akamhy/waybackpy/wiki/Python-package-docs#basic-usage>. We now support the CDX API completely.

I will implement what you asked in #67. Feel free to create more Issues.

**Comment by akamhy** [comment]
Exits as of Jan 2022. Either via the known URL or the CDX API interface.
