### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by akamhy** [akamhy/waybackpy#97]
Too Many Requests
We are limiting the number of URLs you can submit to be Archived to the Wayback Machine, using the Save Page Now features, to no more than 15 per minute.

If you submit more than that we will block Save Page Now requests from your IP number for 5 minutes.

Please feel free to write to us at info@archive.org if you have questions about this. Please include your IP address and any URLs in the email so we can provide you with better service. 

![Too Many Requests Screenshot from 2021-04-24 17-14-23](https://user-images.githubusercontent.com/64683866/115957566-dcfc7080-a520-11eb-8b73-f17a51f1c54e.png)

**Comment by akamhy** [comment]
Nothing to do here, closing.

**Comment by rafaelrdealmeida** [comment]
Hi @akamhy,

does waybackpy handle this (no more than 15 minutes per minute)? or is that the responsibility of the waybackpy user?

cheers

**Comment by akamhy** [comment]
@rafaelrdealmeida waybackpy has an inbuilt delay between the API calls to all of the three APIs. You would never hit the 15 archives per minute limit unless you are running multiple instances of waybackpy(by threading or parallel tasks) on the same IP address.

**Comment by DorAlter** [comment]
Hey @akamhy,

I am getting this error, although I am not sending more than 15 requests per minute.
