### ISSUE TITLE
Error getting a page when the encoding is 'None'

### ISSUE THREAD

**Issue by AlbertoFDR** [akamhy/waybackpy#98]
The error comes on 'wrapper.py' when the encoding is 'None'. Webpage for example of the error "https://akamhy.github.io/". The file that causes the issue has a extension of '.woff2'.

Error:
```
return response.content.decode(encoding.replace("text/html", "UTF-8", 1))
AttributeError: 'NoneType' object has no attribute 'replace'
```

In my case I want to download all the versions of a domain (html, js...) and also subdomains, so to do that I use Cdx and then, I download using the get method.

**Comment by AlbertoFDR** [comment]
+ info:

In my case I want to download all the versions of a domain (html, js...), so to do that I use Cdx and then, I download using the get method.

**Comment by akamhy** [comment]
Get is deprecated. Closing issue.
